#!/usr/bin/env python3
"""
img_to_r5g6b5.py

Convert an image (JPEG/PNG/etc.) to R5G6B5 packed bytes and output a C array
padded to a multiple of 512 bytes.

Output example:
  const u8 image_data[<padded_size>] = { 0x34, 0x12, 0xFF, ... };

Default byte order: little-endian (low byte first). Use --endian big for big-endian.

Requires Pillow: pip install pillow
"""

import argparse
import os
import sys
from textwrap import wrap

try:
    from PIL import Image
except Exception:
    Image = None


def ensure_pillow():
    if Image is None:
        print("Pillow is required. Install with: pip install pillow", file=sys.stderr)
        sys.exit(2)


def rgb_to_r5g6b5_bytes(r, g, b, endian="little"):
    # r,g,b are 0-255
    val = ((r >> 3) & 0x1F) << 11 | ((g >> 2) & 0x3F) << 5 | ((b >> 3) & 0x1F)
    if endian == "little":
        return bytes([val & 0xFF, (val >> 8) & 0xFF])
    else:
        return bytes([(val >> 8) & 0xFF, val & 0xFF])


def image_to_r5g6b5_bytes(img, endian="little"):
    # Ensure RGB (handle alpha by compositing onto white)
    if img.mode == "RGBA" or img.mode == "LA" or ("transparency" in img.info):
        # Composite onto white background
        bg = Image.new("RGB", img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[-1])
        img_rgb = bg
    else:
        img_rgb = img.convert("RGB")

    w, h = img_rgb.size
    out = bytearray()
    px = img_rgb.load()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            out.extend(rgb_to_r5g6b5_bytes(r, g, b, endian=endian))
    return bytes(out), w, h


def make_c_array(data_bytes, array_name="image_data", c_type="u8", line_bytes=12):
    # Format bytes as 0xXX and wrap lines
    hex_bytes = [f"0x{b:02X}" for b in data_bytes]
    lines = []
    for i in range(0, len(hex_bytes), line_bytes):
        lines.append("  " + ", ".join(hex_bytes[i:i+line_bytes]))
    body = ",\n".join(lines)
    return f"const {c_type} {array_name}[{len(data_bytes)}] = {{\n{body}\n}};\n"


def pad_to_block(data_bytes, block=512, pad_value=0x00):
    length = len(data_bytes)
    pad_len = (block - (length % block)) % block
    if pad_len:
        return data_bytes + bytes([pad_value]) * pad_len, pad_len
    return data_bytes, 0


def parse_args():
    p = argparse.ArgumentParser(description="Convert image to R5G6B5 C array padded to multiple of 512 bytes")
    p.add_argument("input", help="Input image file (JPEG, PNG, ...)")
    p.add_argument("-o", "--output", default=None, help="Output C file (default: stdout)")
    p.add_argument("--array-name", default="image_data", help="C array name")
    p.add_argument("--c-type", default="u8", help="C type to use (default: u8). Example: uint8_t)")
    p.add_argument("--endian", choices=("little", "big"), default="little", help="Byte order for 16-bit values (default: little)")
    p.add_argument("--wrap", type=int, default=12, help="Bytes per line in the C array (default: 12)")
    p.add_argument("--pad-value", type=lambda x: int(x,0), default=0, help="Pad byte value (hex or decimal), default 0")
    p.add_argument("--no-size-comment", action="store_true", help="Don't include width/height/size comment header")
    p.add_argument("--test", action="store_true", help="Run a small self-test (generate a 4x4 image and output to stdout)")
    return p.parse_args()


def run(args):
    ensure_pillow()
    if args.test:
        # Create a small test image (4x4) with simple colors
        img = Image.new("RGB", (4,4))
        colors = [ (255,0,0), (0,255,0), (0,0,255), (255,255,0) ]
        px = img.load()
        for y in range(4):
            for x in range(4):
                px[x,y] = colors[(x+y) % len(colors)]
        data, w, h = image_to_r5g6b5_bytes(img, endian=args.endian)
    else:
        if not os.path.isfile(args.input):
            print(f"Input file not found: {args.input}", file=sys.stderr)
            sys.exit(2)
        img = Image.open(args.input)
        data, w, h = image_to_r5g6b5_bytes(img, endian=args.endian)

    original_len = len(data)
    data, pad_len = pad_to_block(data, block=512, pad_value=args.pad_value)
    padded_len = len(data)

    c_array = make_c_array(data, array_name=args.array_name, c_type=args.c_type, line_bytes=args.wrap)

    header = []
    if not args.no_size_comment:
        header.append(f"// Generated by img_to_r5g6b5.py")
        header.append(f"// Source: {os.path.basename(args.input) if not args.test else '<generated-test>'}")
        header.append(f"// Size: {w} x {h}, pixels: {w*h}")
        header.append(f"// Original bytes (un-padded): {original_len}")
        header.append(f"// Padded bytes: {padded_len} (pad added: {pad_len})")
        header.append("")

    out_text = "\n".join(header) + c_array

    if args.output:
        with open(args.output, "w", newline="\n") as f:
            f.write(out_text)
        print(f"Wrote {args.output} (padded size: {padded_len} bytes)")
    else:
        print(out_text)


if __name__ == "__main__":
    args = parse_args()
    run(args)
